name: Lint merge commit name

on:
  push:
    branches-ignore:
      - "master"

jobs:
  lint-commit-name:
    if: contains(github.ref, 'gh-readonly-queue/master/')
    runs-on: ubuntu-latest
    steps:
      - uses: wagoid/commitlint-github-action@v5
        with:
          commitDepth: 1
